### ISSUE TITLE
无法打包/解包文件，似乎都是finfo的问题

### ISSUE THREAD

**Issue by SuperYYT** [pmt-mcpe-fun/website#23]
Fatal error: Uncaught Error: Class 'finfo' not found in /www/wwwroot/www.mcshare.net/pmt/pages/phar2zip/convert.php:36 Stack trace: #0 {main} thrown in /www/wwwroot/www.mcshare.net/pmt/pages/phar2zip/convert.php on line 36

**Comment by Ad5001** [comment]
Hello,
Please note that public instances of this website are not allowed.
In case of a private instance, you need to update it.

**Comment by nathfreder** [comment]
WOT
